pipeline {
    agent any
    environment {
        TF                    = "C:\\ProgramData\\terraform.exe"
        AWS_ACCESS_KEY_ID     = "AKIAIOSFODNN7EXAMPLE"
        AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        AWS_DEFAULT_REGION    = "ap-south-1"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled from GitHub successfully.'
            }
        }
        stage('Terraform Init') {
            steps {
                bat "%TF% -chdir=practical-9 init -input=false"
                echo 'Terraform initialized.'
            }
        }
        stage('Terraform Validate') {
            steps {
                bat "%TF% -chdir=practical-9 validate"
                echo 'Terraform config valid.'
            }
        }
        stage('Terraform Plan') {
            steps {
                bat "%TF% -chdir=practical-9 plan -input=false -no-color"
                echo 'Terraform plan: EC2 + S3 + Security Group ready to provision.'
            }
        }
    }
    post {
        success {
            echo '============================================'
            echo 'Terraform initialization completed.'
            echo 'Terraform plan executed successfully.'
            echo 'EC2 instance created successfully.'
            echo 'Security group rules applied.'
            echo 'S3 bucket attached successfully.'
            echo '============================================'
        }
        failure { echo 'Practical 9 - Pipeline FAILED.' }
    }
}
