pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled from GitHub successfully.'
            }
        }
        stage('Terraform Init') {
            steps {
                bat "terraform -chdir=practical-9 init -input=false"
                echo 'Terraform initialized.'
            }
        }
        stage('Terraform Validate') {
            steps {
                bat "terraform -chdir=practical-9 validate"
                echo 'Terraform config valid.'
            }
        }
        stage('Terraform Plan') {
            steps {
                bat "terraform -chdir=practical-9 plan -input=false -no-color 2>&1"
                echo 'Terraform plan: EC2 + S3 + Security Group ready to provision.'
            }
        }
    }
    post {
        success { echo 'Practical 9 - Terraform EC2+S3 pipeline PASSED!' }
        failure { echo 'Practical 9 - Pipeline FAILED.' }
    }
}
