pipeline {
    agent any
    environment {
        KUBECONFIG = "C:\\ProgramData\\kube\\config"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled from GitHub.'
            }
        }
        stage('Verify Cluster') {
            steps {
                bat "kubectl get nodes"
                echo 'Minikube cluster ready.'
            }
        }
        stage('Build and Load Image') {
            steps {
                bat "docker build -t flask-practical4:latest ./practical-4"
                bat "docker save flask-practical4:latest | docker exec -i minikube docker load"
                echo 'Image loaded into Minikube.'
            }
        }
        stage('Deploy App') {
            steps {
                bat "kubectl apply -f practical-7/deployment.yaml"
                bat "kubectl apply -f practical-7/service.yaml"
                bat "kubectl rollout status deployment/flask-deployment --timeout=120s"
                echo 'Flask app deployed to Kubernetes.'
            }
        }
        stage('Apply HPA') {
            steps {
                bat "kubectl apply -f practical-7/hpa.yaml"
                sleep(time: 5, unit: 'SECONDS')
                bat "kubectl get hpa flask-hpa"
                echo 'HPA configured - min=1 max=5 cpu=50%.'
            }
        }
        stage('Verify') {
            steps {
                bat "kubectl get pods"
                bat "kubectl get deployments"
                bat "kubectl get hpa"
                bat "kubectl get services"
                echo 'All K8s resources verified.'
            }
        }
    }
    post {
        success {
            echo '============================================'
            echo 'Horizontal Pod Autoscaler created successfully.'
            echo 'Deployment is running.'
            echo 'HPA configured with CPU threshold.'
            echo 'Pods scale up/down automatically based on load.'
            echo '============================================'
        }
        failure { echo 'Practical 7 - Pipeline FAILED.' }
    }
}
