pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled from GitHub.'
            }
        }
        stage('Build Original Image') {
            steps {
                bat "docker build -f practical-6/Dockerfile.original -t flask-original:latest ./practical-6"
                echo 'Original (large) image built.'
            }
        }
        stage('Build Optimized Image') {
            steps {
                bat "docker build -f practical-6/Dockerfile.optimized -t flask-optimized:latest ./practical-6"
                echo 'Optimized (slim) image built.'
            }
        }
        stage('Compare Sizes') {
            steps {
                bat "docker images flask-original"
                bat "docker images flask-optimized"
                echo 'Optimized image is significantly smaller!'
            }
        }
        stage('Test Optimized Image') {
            steps {
                script {
                    bat(script: "docker stop flask_p6", returnStatus: true)
                    bat(script: "docker rm flask_p6",   returnStatus: true)
                    bat "docker run -d -p 5004:5000 --name flask_p6 flask-optimized:latest"
                    sleep(time: 4, unit: 'SECONDS')
                    bat "curl -s http://localhost:5004/"
                    bat(script: "docker stop flask_p6", returnStatus: true)
                    bat(script: "docker rm flask_p6",   returnStatus: true)
                }
                echo 'Optimized image runs successfully.'
            }
        }
    }
    post {
        success { echo 'Practical 6 - Docker Optimization pipeline PASSED!' }
        failure { echo 'Practical 6 - Pipeline FAILED.' }
    }
}
