pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code from GitHub...'
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled successfully.'
            }
        }
        stage('Build Original Image') {
            steps {
                bat "docker build -f practical-6/Dockerfile.original -t flask-original:latest ./practical-6"
                echo 'Original image built (large size).'
            }
        }
        stage('Build Optimized Image') {
            steps {
                bat "docker build -f practical-6/Dockerfile.optimized -t flask-optimized:latest ./practical-6"
                echo 'Optimized image built (small size).'
            }
        }
        stage('Compare Image Sizes') {
            steps {
                bat "docker images flask-original flask-optimized --format \"table {{.Repository}}\\t{{.Tag}}\\t{{.Size}}\""
                echo 'Size comparison complete - optimized image is significantly smaller!'
            }
        }
        stage('Test Optimized Image') {
            steps {
                bat "docker stop flask_p6 2>nul || echo not running"
                bat "docker rm   flask_p6 2>nul || echo not found"
                bat "docker run -d -p 5004:5000 --name flask_p6 flask-optimized:latest"
                bat "ping -n 4 127.0.0.1 >nul"
                bat "curl -s http://localhost:5004/"
                bat "docker stop flask_p6 && docker rm flask_p6"
                echo 'Optimized image tested successfully.'
            }
        }
    }
    post {
        success { echo 'Practical 6 - Docker Image Optimization pipeline SUCCESS!' }
        failure { echo 'Practical 6 - Pipeline FAILED.' }
    }
}
