pipeline {
    agent any
    environment {
        IMAGE_NAME = "flask-practical4"
        CONTAINER  = "flask_p4"
        PORT       = "5002"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled from GitHub.'
            }
        }
        stage('Build Docker Image') {
            steps {
                bat "docker build -t %IMAGE_NAME%:latest ./practical-4"
                echo 'Docker image built.'
            }
        }
        stage('Run Container') {
            steps {
                script {
                    bat(script: "docker stop %CONTAINER%", returnStatus: true)
                    bat(script: "docker rm %CONTAINER%",   returnStatus: true)
                    bat "docker run -d -p %PORT%:5000 --name %CONTAINER% %IMAGE_NAME%:latest"
                    sleep(time: 5, unit: 'SECONDS')
                }
                echo 'Container running on port 5002.'
            }
        }
        stage('Test Endpoints') {
            steps {
                bat "curl -s http://localhost:%PORT%/"
                bat "curl -s http://localhost:%PORT%/health"
                bat "curl -s http://localhost:%PORT%/info"
                echo 'All 3 endpoints verified.'
            }
        }
        stage('Cleanup') {
            steps {
                script {
                    bat(script: "docker stop %CONTAINER%", returnStatus: true)
                    bat(script: "docker rm %CONTAINER%",   returnStatus: true)
                }
                echo 'Container cleaned up.'
            }
        }
    }
    post {
        success { echo 'Practical 4 - Docker Flask pipeline PASSED!' }
        failure { echo 'Practical 4 - Pipeline FAILED.' }
    }
}
