pipeline {
    agent any
    environment {
        IMAGE_NAME = "flask-practical4"
        CONTAINER  = "flask_p4"
        PORT       = "5002"
    }
    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code from GitHub...'
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled successfully.'
            }
        }
        stage('Build Docker Image') {
            steps {
                bat "docker build -t %IMAGE_NAME%:latest ./practical-4"
                echo 'Docker image built successfully.'
            }
        }
        stage('Run Container') {
            steps {
                bat "docker stop %CONTAINER% 2>nul || echo container not running"
                bat "docker rm   %CONTAINER% 2>nul || echo container not found"
                bat "docker run -d -p %PORT%:5000 --name %CONTAINER% %IMAGE_NAME%:latest"
                bat "ping -n 4 127.0.0.1 >nul"
                echo 'Container started on port 5002.'
            }
        }
        stage('Test Endpoints') {
            steps {
                bat "curl -s http://localhost:%PORT%/"
                bat "curl -s http://localhost:%PORT%/health"
                bat "curl -s http://localhost:%PORT%/info"
                echo 'All endpoints tested successfully.'
            }
        }
        stage('Cleanup') {
            steps {
                bat "docker stop %CONTAINER%"
                bat "docker rm   %CONTAINER%"
                echo 'Container cleaned up.'
            }
        }
    }
    post {
        success { echo 'Practical 4 - Docker Flask pipeline SUCCESS!' }
        failure { echo 'Practical 4 - Pipeline FAILED.' }
    }
}
