pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled from GitHub successfully.'
            }
        }
        stage('Start Minikube') {
            steps {
                bat "minikube start --driver=docker 2>&1 || echo Minikube already running"
                bat "minikube status"
            }
        }
        stage('Load Image') {
            steps {
                bat "docker build -t flask-practical4:latest ./practical-4"
                bat "minikube image load flask-practical4:latest"
                echo 'Image ready in Minikube.'
            }
        }
        stage('Apply ConfigMap') {
            steps {
                bat "kubectl apply -f practical-8/configmap.yaml"
                bat "kubectl get configmap app-config"
                bat "kubectl describe configmap app-config"
                echo 'ConfigMap created.'
            }
        }
        stage('Deploy Pod') {
            steps {
                bat "kubectl delete pod flask-configmap-pod 2>nul & echo pod cleanup done"
                bat "kubectl apply -f practical-8/pod.yaml"
                bat "ping -n 15 127.0.0.1 >nul"
                bat "kubectl get pod flask-configmap-pod"
                echo 'Pod deployed with ConfigMap injected.'
            }
        }
        stage('Verify Injection') {
            steps {
                bat "kubectl describe pod flask-configmap-pod"
                echo 'ConfigMap env vars injected into pod verified.'
            }
        }
    }
    post {
        success { echo 'Practical 8 - Kubernetes ConfigMap pipeline PASSED!' }
        failure { echo 'Practical 8 - Pipeline FAILED.' }
    }
}
