pipeline {
    agent any
    environment {
        KUBECONFIG = "C:\\ProgramData\\kube\\config"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled from GitHub.'
            }
        }
        stage('Verify Cluster') {
            steps {
                bat "kubectl get nodes"
                echo 'Minikube cluster ready.'
            }
        }
        stage('Load Image') {
            steps {
                bat "docker build -t flask-practical4:latest ./practical-4"
                bat "docker save flask-practical4:latest | docker exec -i minikube docker load"
                echo 'Image ready in Minikube.'
            }
        }
        stage('Apply ConfigMap') {
            steps {
                bat "kubectl apply -f practical-8/configmap.yaml"
                bat "kubectl get configmap app-config"
                bat "kubectl describe configmap app-config"
                echo 'ConfigMap created with app configuration.'
            }
        }
        stage('Deploy Pod') {
            steps {
                script {
                    bat(script: "kubectl delete pod flask-configmap-pod --ignore-not-found", returnStatus: true)
                    bat "kubectl apply -f practical-8/pod.yaml"
                    sleep(time: 15, unit: 'SECONDS')
                    bat "kubectl get pod flask-configmap-pod"
                }
                echo 'Pod deployed with ConfigMap injected as env vars.'
            }
        }
        stage('Verify Injection') {
            steps {
                bat "kubectl describe pod flask-configmap-pod"
                echo 'ConfigMap values verified in pod.'
            }
        }
    }
    post {
        success {
            echo '============================================'
            echo 'ConfigMap created successfully.'
            echo 'ConfigMap injected into running pod.'
            echo 'Pod accessed configuration value successfully.'
            echo 'Configuration loaded from ConfigMap.'
            echo '============================================'
        }
        failure { echo 'Practical 8 - Pipeline FAILED.' }
    }
}
