apiVersion: v1
kind: Pod
metadata:
  name: flask-configmap-pod
  labels:
    app: flask-configmap
spec:
  containers:
  - name: flask-container
    image: flask-practical4:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 5000
    envFrom:
    - configMapRef:
        name: app-config
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
