pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled from GitHub successfully.'
            }
        }
        stage('Terraform Init') {
            steps {
                bat "terraform -chdir=practical-10 init -input=false"
                echo 'Terraform initialized.'
            }
        }
        stage('Terraform Validate') {
            steps {
                bat "terraform -chdir=practical-10 validate"
                echo 'Terraform VPC config valid.'
            }
        }
        stage('Terraform Plan') {
            steps {
                bat "terraform -chdir=practical-10 plan -input=false -no-color 2>&1"
                echo 'Terraform plan: VPC + subnets + IGW + NAT Gateway ready.'
            }
        }
    }
    post {
        success { echo 'Practical 10 - Terraform VPC pipeline PASSED!' }
        failure { echo 'Practical 10 - Pipeline FAILED.' }
    }
}
