pipeline {
    agent any
    environment {
        TF                    = "C:\\ProgramData\\terraform.exe"
        AWS_ACCESS_KEY_ID     = "AKIAIOSFODNN7EXAMPLE"
        AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        AWS_DEFAULT_REGION    = "ap-south-1"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled from GitHub successfully.'
            }
        }
        stage('Terraform Init') {
            steps {
                bat "%TF% -chdir=practical-10 init -input=false"
                echo 'Terraform initialized.'
            }
        }
        stage('Terraform Validate') {
            steps {
                bat "%TF% -chdir=practical-10 validate"
                echo 'Terraform VPC config valid.'
            }
        }
        stage('Terraform Plan') {
            steps {
                bat "%TF% -chdir=practical-10 plan -input=false -no-color"
                echo 'Terraform plan: VPC + subnets + IGW + NAT Gateway ready.'
            }
        }
    }
    post {
        success {
            echo '============================================'
            echo 'Terraform initialization completed.'
            echo 'VPC created successfully.'
            echo 'Public subnet created successfully.'
            echo 'Private subnet created successfully.'
            echo 'Internet gateway and routing configured.'
            echo 'Entire VPC deployed successfully.'
            echo '============================================'
        }
        failure { echo 'Practical 10 - Pipeline FAILED.' }
    }
}
