pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code from GitHub...'
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled successfully.'
            }
        }
        stage('Terraform Init') {
            steps {
                bat "terraform -chdir=practical-10 init"
                echo 'Terraform initialized - AWS provider ready.'
            }
        }
        stage('Terraform Validate') {
            steps {
                bat "terraform -chdir=practical-10 validate"
                echo 'VPC configuration valid.'
            }
        }
        stage('Terraform Plan') {
            steps {
                bat "terraform -chdir=practical-10 plan -out=tfplan"
                echo 'Terraform plan: VPC + public subnet + private subnet + IGW + NAT GW.'
            }
        }
        stage('Show Plan Summary') {
            steps {
                bat "terraform -chdir=practical-10 show tfplan"
                echo 'Plan summary: 8 resources to be created (VPC, subnets, IGW, NAT, route tables).'
            }
        }
    }
    post {
        success { echo 'Practical 10 - Terraform VPC pipeline SUCCESS!' }
        failure { echo 'Practical 10 - Pipeline FAILED.' }
    }
}
