pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled from GitHub successfully.'
            }
        }
        stage('Build Images') {
            steps {
                bat "docker compose -f practical-5/docker-compose.yml build --no-cache"
                echo 'Docker images built.'
            }
        }
        stage('Deploy Containers') {
            steps {
                bat "docker compose -f practical-5/docker-compose.yml down 2>nul & echo down done"
                bat "docker compose -f practical-5/docker-compose.yml up -d"
                bat "ping -n 8 127.0.0.1 >nul"
                echo 'Multi-container app deployed.'
            }
        }
        stage('Test Endpoints') {
            steps {
                bat "curl -s http://localhost:5003/"
                bat "curl -s http://localhost:5003/"
                bat "curl -s http://localhost:5003/"
                bat "curl -s http://localhost:5003/health"
                echo 'Redis counter incrementing - inter-container communication verified.'
            }
        }
        stage('Verify Services') {
            steps {
                bat "docker compose -f practical-5/docker-compose.yml ps"
            }
        }
        stage('Cleanup') {
            steps {
                bat "docker compose -f practical-5/docker-compose.yml down"
                echo 'Containers stopped.'
            }
        }
    }
    post {
        success { echo 'Practical 5 - Docker Compose pipeline PASSED!' }
        failure { echo 'Practical 5 - Pipeline FAILED.' }
    }
}
