pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshmalekar514/devops-practicals.git',
                    credentialsId: 'github-creds'
                echo 'Code pulled from GitHub.'
            }
        }
        stage('Build Images') {
            steps {
                bat "docker compose -f practical-5/docker-compose.yml build --no-cache"
                echo 'Docker images built.'
            }
        }
        stage('Deploy Containers') {
            steps {
                script {
                    bat(script: "docker compose -f practical-5/docker-compose.yml down", returnStatus: true)
                    bat "docker compose -f practical-5/docker-compose.yml up -d"
                    sleep(time: 8, unit: 'SECONDS')
                }
                echo 'Multi-container app deployed.'
            }
        }
        stage('Test Endpoints') {
            steps {
                bat "curl -s http://localhost:5003/"
                bat "curl -s http://localhost:5003/"
                bat "curl -s http://localhost:5003/"
                bat "curl -s http://localhost:5003/health"
                echo 'Redis counter increments - inter-container comms verified.'
            }
        }
        stage('Verify Services') {
            steps {
                bat "docker compose -f practical-5/docker-compose.yml ps"
            }
        }
        stage('Cleanup') {
            steps {
                bat "docker compose -f practical-5/docker-compose.yml down"
                echo 'Containers stopped.'
            }
        }
    }
    post {
        success {
            echo '============================================'
            echo 'Docker Compose file executed successfully.'
            echo 'All containers started.'
            echo 'Services are connected and running.'
            echo 'Application accessible in browser.'
            echo '============================================'
        }
        failure { echo 'Practical 5 - Pipeline FAILED.' }
    }
}
